Feature/25a (#40)
neonevm/neon-tests pull request #42
Opened 2022-04-12 11:40 UTC by apetrovskiy

* Update basic.py

* fixes

* no code

* Update basic.py

* Update test_transfers.py

* Update basic.py

* Update basic.py

* Update test_transfers.py

* Update test_transfers.py

* refactoring

* formatting

* fixes

* formatting

* removal of is_devnet

* Update test_transfers.py

* fixes

* code formatting

* Update test_transfers.py

* Update test_transfers.py

* Update basic.py

* fixes

* Update error_message.py

* more tests

* Update test_transfers.py

* Update test_blocks.py

* Update basic.py

* Update test_transfers.py

* Update test_transfers.py

* Update test_transfers.py

* Update test_transfers.py

* Update test_transfers.py

* Update test_transfers.py

* Update test_transfers.py

* Update basic.py

* Update test_transfers.py

* Update test_transfers.py

* Update test_transfers.py

* Update test_transfers.py

* fixes and more tests

* Update error_message.py

* code clean-up

2022-04-14 11:11 UTC, gigimon requested changes
You have a lot unfinished cases in test_single_client_activity.py

2022-04-14 11:11 UTC, gigimon commented on integration/tests/basic/test_transactions_validation.py
> +import allure
move this to test_transactions

2022-04-14 11:11 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +from re import U
merge this file with test_transactions in separate class. Transfers - transactions too

2022-04-14 11:11 UTC, gigimon commented on integration/tests/basic/test_transactions.py
> +    @pytest.mark.skip("in progress")
test_transactions

2022-04-14 11:11 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +        """Too low gas_limit"""
use pytest.parametrize for next 4 cases

2022-04-14 12:33 UTC, apetrovskiy commented on integration/tests/basic/test_transactions_validation.py
> +import allure
done

2022-04-14 13:06 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +from re import U
done

2022-04-14 13:08 UTC, apetrovskiy commented on integration/tests/basic/test_transactions.py
> +    @pytest.mark.skip("in progress")
done

2022-04-14 15:23 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +        """Too low gas_limit"""
done

2022-04-18 08:27 UTC, gigimon requested changes

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
>                  assert None != error_info, "Transaction failed"
else with raise will more logic

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +    def test_rpc_call_eth_getTransactionCount(self, prepare_accounts):
this test must be in test_rpc_calls because only  run rpc_call

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +12.	Verify implemented rpc calls work
rpc calls tests must be in test_rpc_calls, why you move it here?

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +    def test_rpc_call_eth_sendRawTransaction(self, prepare_accounts):
Why this tests here and not in TestTransfers? Also we need a more negative cases (bad gas, galimit, nonce, from/to)

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +    def test_rpc_call_eth_getTransactionByHash(self, prepare_accounts):
Why rpc_call tests here?

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +        """Check ERC-1820 transaction (without chain_id in sign)"""
why not in TestTransfers?

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +class TestRpcCallsTransactionsValidation(BasicTests):
Why it's this tests not in TestTransfers?

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +    def test_there_are_not_enough_neons_for_gas_fee(self):
Why not enough gas here but bad nonce in another suite?

2022-04-18 08:27 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +        model = RpcRequestFactory.get_send_raw_trx(params=params)
what "get_send_raw_trx" do? get or send transaction?

2022-04-29 06:29 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
>                  assert None != error_info, "Transaction failed"
done

2022-04-29 06:29 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +    def test_rpc_call_eth_getTransactionCount(self, prepare_accounts):
done

2022-04-29 06:29 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +12.	Verify implemented rpc calls work
done

2022-04-29 06:29 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +    def test_rpc_call_eth_sendRawTransaction(self, prepare_accounts):
done

2022-04-29 06:29 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +        """Check ERC-1820 transaction (without chain_id in sign)"""
done

2022-04-29 06:29 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +class TestRpcCallsTransactionsValidation(BasicTests):
done

2022-04-29 06:30 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +    def test_there_are_not_enough_neons_for_gas_fee(self):
done

2022-04-29 06:30 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +        model = RpcRequestFactory.get_send_raw_trx(params=params)
refactored

2022-04-29 08:29 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +    def test_rpc_call_eth_getTransactionByHash(self, prepare_accounts):
done

2022-04-29 11:49 UTC, gigimon requested changes

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +        """Deploys an ERC-20 contract"""
Empty function

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
>              with pytest.raises(Exception) as error_info:
You can use match in pytests.raises
https://docs.pytest.org/en/6.2.x/assert.html#assertraises

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
>      def deploy_contract(self):
??

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    # TODO: check it
remove TODO

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +        contract_interface = helpers.get_contract_interface(contract_name, version)
We already have this in https://github.com/neonlabsorg/neon-tests/blob/develop/integration/tests/economy/test_economics.py#L59
Move it to utils

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    # TODO: probe
comments

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/helpers/error_message.py
> +    INSUFFICIENT_FUNDS = "insufficient funds for transfer"
Which difference between this file and integration/tests/basic/helpers/assert_message.py ?
Both of this has error messages from transactions

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/test_data/input_data.py
> +    FIRST_AMOUNT_IN_RESPONSE = "0x4563918244f40000"
what is magic value? I can't find usages

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/test_single_client_activity.py
> +    def test_check_tokens_in_wallet_spl(self, erc20wrapper):
This test doesn't check spl, it use only erc20 contract because You deploy ERC20 and interact only with it, You don't use contract from erc20wrapper. And this tests already exist in test_transfers

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/test_single_client_activity.py
> +        initial_sender_neon_balance = float(
this test equal to previous

2022-04-29 11:49 UTC, gigimon commented on package-lock.json
> +{
why you create this file?

2022-04-29 11:49 UTC, gigimon commented on package.json
> +{}
remove this too

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +        """Send spl wrapped account from one account to another
will be good if we will check balance in spl account too

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +        assert error_info, AssertMessage.TRX_NOT_FAILED.value
don't need this, because pytest.raises will raise

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +        assert initial_recipient_neon_balance >= float(
recipient balance must be =, not >

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +        # TODO: should the ERC20 balance be decreased or be the same as before the transaction?
resolve this TODO

2022-04-29 11:49 UTC, gigimon commented on integration/tests/basic/test_single_client_activity.py
> +20.	Check ERC-1820 transaction (without chain_id in sign)
maybe move thos doc to test_transfer?

2022-04-29 13:41 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +        """Deploys an ERC-20 contract"""
fixed

2022-04-29 13:41 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
>      def deploy_contract(self):
fixed (I used the existing call instead)

2022-04-29 13:42 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    # TODO: check it
done

2022-04-29 13:44 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +        # TODO: should the ERC20 balance be decreased or be the same as before the transaction?
ok

2022-04-29 15:12 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +        assert initial_recipient_neon_balance >= float(
fixed

2022-04-29 15:15 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +        assert error_info, AssertMessage.TRX_NOT_FAILED.value
fixed

2022-04-29 16:01 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +        """Send spl wrapped account from one account to another
already done

2022-04-29 16:54 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
>              with pytest.raises(Exception) as error_info:
done

2022-04-29 17:01 UTC, apetrovskiy commented on integration/tests/basic/test_single_client_activity.py
> +20.	Check ERC-1820 transaction (without chain_id in sign)
I removed them completely as everything or almost everything is covered

2022-04-29 17:04 UTC, apetrovskiy commented on integration/tests/basic/helpers/error_message.py
> +    INSUFFICIENT_FUNDS = "insufficient funds for transfer"
assert_message is used for instructions like
assert statement, AssertMessage.COMMENT
and contains just descriptions

error_message contains what is searched in exceptions (parts of error response)

2022-04-29 17:06 UTC, apetrovskiy commented on integration/tests/basic/test_data/input_data.py
> +    FIRST_AMOUNT_IN_RESPONSE = "0x4563918244f40000"
At the time of first version this value was returned for transaction with a specific amount.
Now it seems not to be in use, delted

2022-04-29 17:25 UTC, apetrovskiy commented on integration/tests/basic/test_single_client_activity.py
> +        initial_sender_neon_balance = float(
fixed

2022-04-29 17:25 UTC, apetrovskiy commented on integration/tests/basic/test_single_client_activity.py
> +    def test_check_tokens_in_wallet_spl(self, erc20wrapper):
fixed

2022-04-29 18:23 UTC, apetrovskiy commented on package.json
> +{}
npm ci won't work without it

2022-05-11 11:26 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    # TODO: probe
fixed

2022-05-11 11:26 UTC, apetrovskiy commented on package-lock.json
> +{
to have basic test fixed (and economy tests as well)
It's a temporary solution, until it's fixed

2022-05-12 12:34 UTC, apetrovskiy commented on package-lock.json
> +{
removed

2022-05-12 12:34 UTC, apetrovskiy commented on package.json
> +{}
removed

2022-05-18 15:00 UTC, gigimon approved these changes

2022-05-18 15:00 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +from typing import Any, Optional, Tuple, Union
use import typing as tp or from typing import Any, Optional, Tuple, Union

2022-05-18 15:00 UTC, gigimon commented on integration/tests/basic/test_single_client_activity.py
> +            wait_at_most(TWO_SECONDS).poll_delay(TWO_SECONDS).until(lambda: True)
What difference  wait_at_most with time.sleep here? And why we need here this wait_at_most?

2022-05-18 15:00 UTC, gigimon commented on integration/tests/basic/test_transfers.py
> +EIP55_INVALID_CHECKSUM = (
Why in this message single quote too?

2022-05-18 15:00 UTC, gigimon commented on utils/faucet.py
> +        wait_at_most(TWO_MINUTES).poll_interval(TEN_SECONDS + ONE_SECOND).until(
busypie library for async code, in this case it work synchronous and wait 2 minutes after than lambda finished or not?

2022-05-19 07:38 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +from typing import Any, Optional, Tuple, Union
done

2022-05-19 07:39 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +from typing import Any, Optional, Tuple, Union
done

2022-05-19 07:57 UTC, apetrovskiy commented on utils/faucet.py
> +        wait_at_most(TWO_MINUTES).poll_interval(TEN_SECONDS + ONE_SECOND).until(
busypie supports both sync and async as they claim.
the code repeats the request every 11 seconds during 2 minutes' interval.
2 minutes as maximum value taken for the case when we run tests in parallel (from the same API)
Anyway, this works

2022-05-19 08:03 UTC, gigimon commented on utils/faucet.py
> +        wait_at_most(TWO_MINUTES).poll_interval(TEN_SECONDS + ONE_SECOND).until(
@apetrovskiy and why we need this every time for request_neon?

2022-05-19 09:02 UTC, apetrovskiy commented on integration/tests/basic/test_transfers.py
> +EIP55_INVALID_CHECKSUM = (
This is what tests searches for in the error message. I can search for address only, skipping ENS name: ' and ' is invalid.

2022-05-19 09:02 UTC, apetrovskiy commented on utils/faucet.py
> +        wait_at_most(TWO_MINUTES).poll_interval(TEN_SECONDS + ONE_SECOND).until(
Changed to poll interval 5 seconds during the time of 2 minutes

2022-05-19 09:31 UTC, apetrovskiy commented on integration/tests/basic/test_single_client_activity.py
> +            wait_at_most(TWO_SECONDS).poll_delay(TWO_SECONDS).until(lambda: True)
changes to time.sleep and moved into the faucet class

2022-05-19 12:35 UTC, merged