Feature/254 basic integration tests for transactions and accounts
neonevm/neon-tests pull request #5
Opened 2022-02-18 06:24 UTC by apetrovskiy

2022-02-18 06:25 UTC, apetrovskiy commented on clickfile.py
> +# @click.option('-n', '--network', default="release-stand", type=click.Choice(networks), help="In which stand run tests")
The only way I found how to use release-stand

2022-02-18 06:25 UTC, apetrovskiy commented on clickfile.py
> +    # command += f" --network={network}"
This didn't work for me

2022-02-18 06:25 UTC, apetrovskiy commented on integration/tests/base.py
> +    # sol_client: solana.rpc.api.Client
These dependencies didn't work for me

2022-02-18 10:10 UTC, gigimon commented on clickfile.py
> +    # command += f" --network={network}"
why and which error was?

2022-02-18 10:11 UTC, gigimon commented on integration/tests/conftest.py
> +#     return loop.run_until_complete(get_price())
which error was? Because this doesn't use current stand and goes to solana mainnet

2022-03-08 09:15 UTC, gigimon requested changes
looks very heavy for simple rpc calls.
1. A lot of files and helpers created only for one time uses
2. More non python way
3. A small count of tests in compare with helpers code
4. A very big count allure steps - it create a noise in the reports.

2022-03-08 09:15 UTC, gigimon commented on envs.json
> +    "operator_neon_rewards_address": [],
already exist in file

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +import allure
file already in "helpers" module, use this name in name is bad naming

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +FIRST_AMOUNT_IN_RESPONSE = '0x4563918244f40000'
this constant used one time in another module, why it here?

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +# TODO: remove it later
later when?

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +    def create_account_with_balance(self, amount: int) -> Account:
use here as default FIRST_FAUCET_REQUEST_AMOUNT and you don't need to use this in 10+ places

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +    def process_transaction(
it's not process transactions, right name: transfer_neon or send_neon

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +        if error_info != None:
with pytest.raises(Exception) as error_info can't be null after "with" because if exception didn't raised pytest raise new exception

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +            assert None != error_info, "Transaction failed"
why we need this assertion?

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +            message: str = "") -> Union[web3.types.TxReceipt, None]:
message parameter unused

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +    @allure.step("transferring tokens")
why we need this? it's equal to self.process_transaction

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +    def transfer_zero_neon(self, sender_account: Account,
we don't need helper method for each simple situation. This method equal to transfer_neon with amount=0

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +
a lot of methods in this helper class useless. And only increase code lines

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +        except Exception:
which exception can be here? If "result" not a member of data, check it before:
```python
return hasattr(data, "result") and data.result != None
```

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/basic_helpers.py
> +            return data.error == None
some previous

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/json_rpc_requester.py
> +class JsonRpcRequester:
we really need this? Or this class created only for allure steps?

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/helpers/rpc_request_params_factory.py
> +class RpcRequestParamsFactory:
i don't understand why we need this. Factory on Factory very Java style :)

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/model/call_request.py
> +    from1: List[str] = None
maybe from_ more pretty

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/model/get_logs_request.py
> +@dataclass
this model used one time...

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/model/call_request.py
> +from dataclasses import dataclass
in my opinion we can use one file models for all this data classes

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/model/call_request.py
> +    gasPrice: int = None
gasPrice is not python like notation

2022-03-08 09:15 UTC, gigimon commented on integration/tests/basic/model/json_rpc_methods.py
> +class JsonRpcMethods(Enum):
this's useless class because each member used only once in RpcRequestFactory. Moreover this values never will change.

2022-03-09 06:20 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic_helpers.py
> +FIRST_AMOUNT_IN_RESPONSE = '0x4563918244f40000'
fixed

2022-03-09 06:20 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic_helpers.py
> +    def create_account_with_balance(self, amount: int) -> Account:
fixed

2022-03-09 06:22 UTC, apetrovskiy commented on integration/tests/basic/model/call_request.py
> +    from1: List[str] = None
fixed

2022-03-09 12:35 UTC, apetrovskiy commented on integration/tests/basic/model/call_request.py
> +    gasPrice: int = None
fixed everywhere

2022-03-09 12:36 UTC, apetrovskiy commented on integration/tests/basic/model/call_request.py
> +    gasPrice: int = None
excepting for the 'from' field, there's need a separate solution

2022-03-10 13:20 UTC, apetrovskiy commented on integration/tests/basic/model/call_request.py
> +from dataclasses import dataclass
fixed

2022-03-10 13:21 UTC, apetrovskiy commented on integration/tests/basic/model/json_rpc_methods.py
> +class JsonRpcMethods(Enum):
it's a classical Enum, not a general class. Enum entries aren't for changes

2022-03-10 13:54 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic_helpers.py
> +import allure
fixed

2022-03-11 13:16 UTC, gigimon requested changes

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +            print("<<<<<<<<<<<<<<<<<")
print?

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +            message: str = "") -> Union[web3.types.TxReceipt, None]:
message unused parameter and this function useless

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    def transfer_zero_neon(self, sender_account: Account,
method has name: transfer_zero_neon but it accept required argument amount. This method useless

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    def transfer_negative_neon(
this useless too

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +            self, sender_account: Account, recipient_account: Account,
useless

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    @allure.step("checking in case the balance is less than required")
useless method, because used only once

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    def assert_amount(self,
3 identical methods below which has only different messages

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    @allure.step("checking that the result subobject is present")
use hasattr

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    def calculate_trx_gas(self, tx_receipt: web3.types.TxReceipt) -> Decimal:
why multiplicate to 0.000_000_000_000_000_001?

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/model/json_rpc_methods.py
> +class JsonRpcMethods(Enum):
Yes, i see Enum, but comment actual for this

2022-03-11 13:16 UTC, gigimon commented on integration/tests/basic/test_rpc_calls.py
> +    @allure.step("test: verify implemented rpc calls work eth_call")
You don't need to use allure.step, allure automatically use help string for description and just left method name (will easy find test from allure report)

2022-03-11 15:44 UTC, apetrovskiy commented on integration/tests/basic/model/json_rpc_methods.py
> +class JsonRpcMethods(Enum):
I removed this Enum in favour of a set of constants

2022-03-11 15:45 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +            print("<<<<<<<<<<<<<<<<<")
just a debug line, to make the output easily recognisable.Removed time ago

2022-03-11 15:48 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +            message: str = "") -> Union[web3.types.TxReceipt, None]:
the message param has been removed, the method is for allure representation

2022-03-11 15:50 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    def transfer_zero_neon(self, sender_account: Account,
yep, the amount param is useless and is removed. The method is for displaying info in allure

2022-03-14 06:01 UTC, apetrovskiy commented on integration/tests/basic/model/call_request.py
> +    gasPrice: int = None
the from field is also fixed

2022-03-14 06:21 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    def calculate_trx_gas(self, tx_receipt: web3.types.TxReceipt) -> Decimal:
just to make the assertion working. What is a better solution?

2022-03-14 06:33 UTC, apetrovskiy commented on integration/tests/basic/helpers/json_rpc_requester.py
> +class JsonRpcRequester:
are you joking me? This class is for sending requests and serialisation/deserialisation.
Do you suggest doing this in each other test?

2022-03-14 06:41 UTC, gigimon commented on integration/tests/basic/helpers/json_rpc_requester.py
> +class JsonRpcRequester:
I don't see any useful things from this except work with models and for allure reports. If You decide this's good solution - ok

2022-03-14 06:43 UTC, gigimon commented on integration/tests/basic/helpers/basic.py
> +    def calculate_trx_gas(self, tx_receipt: web3.types.TxReceipt) -> Decimal:
What you mean? I don't understand. How multiplicate to this helps to assert?

2022-03-14 13:34 UTC, apetrovskiy commented on integration/tests/basic/helpers/rpc_request_params_factory.py
> +class RpcRequestParamsFactory:
The firstly mentioned pattern in Sammerfield's book, btw :)

2022-03-14 14:12 UTC, apetrovskiy commented on integration/tests/basic/test_rpc_calls.py
> +    @allure.step("test: verify implemented rpc calls work eth_call")
fixed

2022-03-14 14:13 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic_helpers.py
> +# TODO: remove it later
removed

2022-03-14 16:12 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    def calculate_trx_gas(self, tx_receipt: web3.types.TxReceipt) -> Decimal:
fixed

2022-03-14 16:12 UTC, apetrovskiy commented on integration/tests/basic/test_rpc_calls.py
> +    @allure.step("test: verify implemented rpc calls work eth_call")
fixed

2022-03-14 16:13 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    @allure.step("checking that the result subobject is present")
fixed

2022-03-16 07:07 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +            self, sender_account: Account, recipient_account: Account,
It was for readability of test methods, now it's removed

2022-03-16 07:08 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    def transfer_negative_neon(
This method served for readability inside test methods. I removed it.

2022-03-16 07:09 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    def transfer_zero_neon(self, sender_account: Account,
The method is removed, it was intended to increase readability inside test methods.

2022-03-18 11:51 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +    def assert_amount(self,
three methods have been merged into one

2022-03-18 11:52 UTC, apetrovskiy commented on integration/tests/basic/helpers/basic.py
> +            message: str = "") -> Union[web3.types.TxReceipt, None]:
fixed some time ago

2022-03-18 11:52 UTC, apetrovskiy commented on integration/tests/basic/model/get_logs_request.py
> +@dataclass
everything or almost everything fixed

2022-03-19 07:31 UTC, apetrovskiy commented on integration/tests/basic/helpers/json_rpc_requester.py
> +class JsonRpcRequester:
I removed any extra allure steps. Now it's event not so easy to understand what's going on if I run these tests against DevNet.
The class itself contains method useful and necessary for working with Json-RPC

2022-03-19 07:33 UTC, apetrovskiy commented on integration/tests/basic/helpers/rpc_request_params_factory.py
> +class RpcRequestParamsFactory:
'factory' is just widely acceptable name of a creator class. In fact, parameters of some Json-PC calls contain data of different types and collected into one list with an order, so it's easy to make a mistake if we just create a list each time.

2022-03-21 13:26 UTC, apetrovskiy commented on clickfile.py
> +    # command += f" --network={network}"
it's outdated now

2022-03-21 13:26 UTC, apetrovskiy commented on integration/tests/conftest.py
> +#     return loop.run_until_complete(get_price())
it's outdated

2022-03-21 14:13 UTC, apetrovskiy commented on clickfile.py
> +# @click.option('-n', '--network', default="release-stand", type=click.Choice(networks), help="In which stand run tests")
it's legacy

2022-03-24 11:22 UTC, gigimon approved these changes

2022-03-24 11:22 UTC, merged