MetaMask base UI tests
neonevm/neon-tests pull request #55
Opened 2022-05-17 14:18 UTC by stunko

2022-05-24 11:12 UTC, gigimon requested changes
Ok, it's work. Cleanup old file (from previous project) and make a good test

2022-05-24 11:12 UTC, gigimon commented on conftest.py
> +pytest_plugins = ["ui.plugins.browser"]
this must be in conftest.py inside ui module

2022-05-24 11:12 UTC, gigimon commented on ui/components/extjs.py
> +
rename file, we don't have extjs :)
Remove all components too, looks like it's copy-paste

2022-05-24 11:12 UTC, gigimon commented on ui/components/react.py
> +import typing as tp
this file like previous (use one file for components)

2022-05-27 09:17 UTC, gigimon requested changes

2022-05-27 09:17 UTC, gigimon commented on deploy/requirements/prod.txt
> +pyperclip3
fix version too

2022-05-27 09:17 UTC, gigimon commented on ui/conftest.py
> +    parser.addoption("--network", action="store", default="devnet", help="Which stand use")
I think we can move it from all tests to common conftest.py in root directory of repo

2022-05-27 09:17 UTC, gigimon commented on ui/conftest.py
> +def use_persistent_context() -> bool:
remove this useless code

2022-05-27 09:17 UTC, gigimon commented on integration/tests/conftest.py
> +def pytest_sessionstart(session):
add comment for this, what is?

2022-05-27 09:17 UTC, gigimon commented on ui/pages/neon_faucet.py
> +    def test_airdrop(self, token: str, amount: tp.Union[int, str]) -> None:
rename this method, because it's not a test

2022-05-27 09:17 UTC, gigimon commented on ui/tests/test_metamask.py
> +        print(f"{10*'+'} Before: {balance_before}, After: {balance_after}")
insert assert here, that after > before

2022-05-27 09:17 UTC, gigimon commented on ui/tests/test_metamask.py
> +def metamask_user_data(metamask_dir: pathlib.Path) -> pathlib.Path:
i think it's useful for all future tests? and must be on conftest or in browser plugin

2022-05-27 09:17 UTC, gigimon commented on ui/tests/test_metamask.py
> +def use_persistent_context() -> bool:
? maybe remove it

2022-05-27 09:17 UTC, gigimon commented on ui/tests/test_metamask.py
> +def context(
and context must be in conftest?

2022-05-31 10:57 UTC, stunko commented on conftest.py
> +pytest_plugins = ["ui.plugins.browser"]
In the first iteration of the code, the plugin initialization was in the ui tests level, but when the tests were run, the pytest reported that it was necessary to move the initialization to the top level

2022-05-31 11:04 UTC, stunko commented on ui/conftest.py
> +    parser.addoption("--network", action="store", default="devnet", help="Which stand use")
This option is initialized at different levels as it has a different default value for different tests
https://github.com/neonlabsorg/neon-tests/blob/feature/base-ui-tests/integration/tests/conftest.py#L44
https://github.com/neonlabsorg/neon-tests/blob/feature/base-ui-tests/ui/conftest.py#L18

2022-05-31 11:06 UTC, stunko commented on ui/conftest.py
> +def use_persistent_context() -> bool:
This fixture is a flag used in https://github.com/neonlabsorg/neon-tests/blob/feature/base-ui-tests/ui/plugins/browser.py#L137 to initialize pages with different behavior

2022-05-31 11:09 UTC, stunko commented on integration/tests/conftest.py
> +def pytest_sessionstart(session):
This fixture was created to clear the log of erroneous launches of the pнtest used in the notification slack tool

2022-05-31 11:22 UTC, stunko commented on ui/tests/test_metamask.py
> +def use_persistent_context() -> bool:
the value of this flag determines how the metamask page will be initialized

2022-05-31 11:23 UTC, stunko commented on ui/tests/test_metamask.py
> +def context(
Override default context https://github.com/neonlabsorg/neon-tests/blob/feature/base-ui-tests/ui/plugins/browser.py#L120 for MetaMasks load

2022-05-31 12:31 UTC, gigimon approved these changes

2022-05-31 12:31 UTC, gigimon commented on clickfile.py
> +"""Relative path where ui tests extensions data stored
use comment (# after constant)

2022-05-31 12:31 UTC, gigimon commented on integration/tests/conftest.py
> +        path = pathlib.Path(f"{clickfile.CMD_ERROR_LOG}")
I think we must move pytest_sessionstart and pytest_runtest_protocol to global conftest.py, because it works only with make-report option

2022-05-31 12:31 UTC, gigimon commented on integration/tests/conftest.py
> +
I think we can move --envs options to global conftest too with this: https://github.com/neonlabsorg/neon-tests/blob/develop/integration/tests/conftest.py#L45 section

2022-05-31 12:31 UTC, gigimon commented on ui/tests/test_metamask.py
> +def use_persistent_context() -> bool:
I think we can remove it, because uses only True value in all tests

2022-05-31 12:31 UTC, gigimon commented on ui/plugins/browser.py
> +    return None
? browser_name always None? Maybe remove this and all is_* fixtures?

2022-05-31 12:31 UTC, gigimon commented on ui/pages/neon_faucet.py
> +    def test_airdrop(self, token: str, amount: tp.Union[int, str]) -> None:
rename!

2022-05-31 12:31 UTC, gigimon commented on ui/tests/test_metamask.py
> +NEON_DEV_NET = "NeonEVM DevNet"
why? You have https://github.com/neonlabsorg/neon-tests/pull/55/files#diff-e89a8cea5199e96f00a43c3ffa96e43c1fa4fd855edc7ad43c4bf75f9db96f1fR12

2022-05-31 13:32 UTC, gigimon approved these changes

2022-05-31 13:32 UTC, merged