NDEV-629: CI/CD for all dApps
neonevm/neon-tests pull request #92
Opened 2022-09-20 12:15 UTC by stunko

2022-10-13 10:47 UTC, gigimon requested changes

2022-10-13 10:47 UTC, gigimon commented on .github/actions/python-requirements/action.yml
> +    - name: Use Node.js 16
Why we install node if install only pyhton-requirements (by name)?

2022-10-13 10:47 UTC, gigimon commented on .github/actions/requirements/action.yml
> +      run: "pip install click requests web3 py-solc-x"
why we install web3 here? If we have action for install python requirements

2022-10-13 10:47 UTC, gigimon commented on .github/workflows/dapps.yml
> +      - name: Launch uniswap tests
Uniswap must be another job with depends from infrastructure to future parallelism

2022-10-13 10:47 UTC, gigimon commented on deploy/aws/test.json
> +{"solana_url": "1.1.1.1"}
remove

2022-10-13 11:54 UTC, stunko commented on .github/actions/requirements/action.yml
> +      run: "pip install click requests web3 py-solc-x"
in with action we have code `./clickfile.py requirements`. clickfile have some import that imports web3 py-solc-x, but in with moment we don't install with requirements. without  thats modules, after merge all GHA action will be failed

2022-10-17 12:53 UTC, gigimon requested changes

2022-10-17 12:53 UTC, gigimon commented on .github/workflows/dapps.yml
> +      - name: Prepare accounts
prepare accounts in each dapps. Because:
1. we need unique accounts for each dapp (for debug)
2. different dapp need different count of accounts

2022-10-17 12:53 UTC, gigimon commented on .github/workflows/dapps.yml
> +          cat $ssh_key
don't show key...

2022-10-17 14:41 UTC, gigimon approved these changes

2022-10-18 13:18 UTC, gigimon approved these changes

2022-10-18 13:18 UTC, gigimon commented on .github/workflows/dapps.yml
> +        if: ${{ steps.requirements.outcome == 'success' }}
don't need use "if" in all steps. If any step failed - next step failed too

2022-10-18 13:18 UTC, gigimon commented on .github/workflows/dapps.yml
> +    if: ${{ success() }}
if useless

2022-10-20 12:57 UTC, merged